[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/api/status-options"
  protocol = "http"
  tls_skip_verify = false

[processes]
  app = "poetry run fastapi run app/main.py --host 0.0.0.0 --port 8000"
